###

GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/6848e4edf4cc1c72c9206b2f

###

POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "postFirstname",
    "lastName": "postupdate",
    "email": "postupdate@gmail.com",
    "favoriteColor": "Green",
    "birthday": "2004-08-22"
}

###

PUT http://localhost:3000/contacts/6848e4edf4cc1c72c9206b2f
Content-Type: application/json

{
    "firstName": "put update",
    "lastName": "postupdate",
    "email": "postupdate@gmail.com",
    "favoriteColor": "Green",
    "birthday": "2004-08-22"
}


###
DELETE http://localhost:3000/contacts/6848e4edf4cc1c72c9206b2f
